// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025 realvirtual GmbH <https://realvirtual.io>

/**
 * library-manifest-sync — the bundled library folder and `library/catalog.json`
 * must agree, and the demo must not own either of them.
 *
 * ## What this guarded before, and why it changed (plan-737)
 *
 * Until plan-737 the demo manifest carried one `library/…` document row per
 * bundled GLB — 17 of them — generated by
 * `scripts/build-local-library-catalog.mjs` and checked in, and this test
 * guarded that list against the folder. That made the demo project the OWNER of
 * the shipped library, which is exactly what plan-737 decided against: the
 * library is APP-LEVEL (`public/library/`, one copy, delivered by
 * `DELIVERED_LIBRARY_CATEGORIES`) and the demo is one subscriber among
 * potentially many, through its `libraries[]`.
 *
 * So the rows are gone, and with them `syncManifestLibraryRows()`. What still
 * has to hold — and is guarded here — is the pair the runtime actually depends
 * on: the catalog mirrors the folder, and a catalog entry's id is the stable
 * derivation every baked `AssetReference.assetId` was minted from. Plus the new
 * invariant that keeps ownership where the decision put it: the demo manifest
 * subscribes and declares no `library/` document of its own.
 */

import { describe, it, expect } from 'vitest';
import { readFile, stat } from 'node:fs/promises';
import { join } from 'node:path';
import {
  ROOT,
  LIBRARY_DIR,
  OUTPUT,
  collectGlbs,
  gitIgnored,
  libraryAssetId,
} from '../scripts/build-local-library-catalog.mjs';

interface CatalogEntry { id?: string; glbUrl?: string }
interface ManifestDoc { id?: string; path?: string }

const DEMO_MANIFEST = join(ROOT, 'public', 'demo-realvirtual', 'project.json');

async function exists(p: string): Promise<boolean> {
  try { await stat(p); return true; } catch { return false; }
}

describe('library catalog sync', () => {
  it('public/library/catalog.json mirrors public/library exactly', async () => {
    if (!await exists(LIBRARY_DIR) || !await exists(OUTPUT)) return; // fork without the bundled library

    const scanned = (await collectGlbs(LIBRARY_DIR)).sort();
    const ignored = gitIgnored(scanned);
    const wanted = scanned.filter(rel => !ignored.has(rel));
    const wantedUrls = wanted.map(rel => rel.split(/[\\/]/).join('/')).sort();

    const catalog = JSON.parse(await readFile(OUTPUT, 'utf8')) as { entries?: CatalogEntry[] };
    const entries = catalog.entries ?? [];
    const haveUrls = entries.map(e => e.glbUrl ?? '').sort();

    expect(
      wantedUrls.filter(u => !haveUrls.includes(u)),
      'library files without a catalog entry — run: node scripts/build-local-library-catalog.mjs',
    ).toEqual([]);
    expect(
      haveUrls.filter(u => !wantedUrls.includes(u)),
      'catalog entries without a library file — run: node scripts/build-local-library-catalog.mjs',
    ).toEqual([]);

    // One entry per file, and every entry addressable: ids must be unique.
    const ids = entries.map(e => e.id ?? '');
    expect(new Set(ids).size, 'duplicate catalog entry ids').toBe(ids.length);

    // The identity contract: an entry's id is the stable derivation, so every
    // `AssetReference.assetId` a planner scene baked against this catalog keeps
    // resolving by identity rather than only through its path fallback.
    const wantedById = new Map(wanted.map(rel => [rel.split(/[\\/]/).join('/'), libraryAssetId(rel)] as const));
    for (const e of entries) {
      expect(e.id, `catalog id for ${e.glbUrl} drifted — run: node scripts/build-local-library-catalog.mjs`)
        .toBe(wantedById.get(e.glbUrl ?? ''));
    }
  });

  it('the demo project subscribes to the library and owns no part of it', async () => {
    if (!await exists(DEMO_MANIFEST)) return;

    const manifest = JSON.parse(await readFile(DEMO_MANIFEST, 'utf8')) as {
      documents?: ManifestDoc[];
      libraries?: { url?: string }[];
    };

    // Ownership, negatively: not one `library/` document row (plan-737 F7).
    const owned = (manifest.documents ?? [])
      .map(d => d.path ?? '')
      .filter(p => p.toLowerCase().startsWith('library/'));
    expect(owned, 'the demo manifest must not declare library documents — the library is app-level').toEqual([]);

    // Subscription, positively: the app-level catalog, DEPLOY-ROOT-relative.
    // Not `demo-realvirtual/library/…` — the catalog sits beside the demo
    // folder, not inside it, and the URL is resolved against the page base
    // rather than through the demo backend's base path.
    const urls = (manifest.libraries ?? []).map(l => l.url ?? '');
    expect(urls).toContain('library/catalog.json');
  });
});
