// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025 realvirtual GmbH <https://realvirtual.io>

/**
 * Guard for the generated private-dependent test list (community parity).
 *
 * `tests/private-dependent-tests.json` + the tsconfig exclude block decide which
 * tests the COMMUNITY edition (no private sibling) skips. Both are generated by
 * scripts/gen-private-test-excludes.mjs. This test recomputes the scan and fails
 * when a test gained or lost a private import without the list being regenerated
 * — the fix is always: `node scripts/gen-private-test-excludes.mjs`.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
// eslint-disable-next-line import/extensions
import { computePrivateDependentTests } from '../scripts/gen-private-test-excludes.mjs';

const ROOT = resolve(__dirname, '..');

describe('private-dependent test excludes (community parity)', () => {
  const expected = computePrivateDependentTests(ROOT);

  it('tests/private-dependent-tests.json matches the actual private imports', () => {
    const listed = JSON.parse(readFileSync(resolve(ROOT, 'tests/private-dependent-tests.json'), 'utf8'));
    expect(listed).toEqual(expected);
  });

  it('tsconfig.json exclude block matches the list', () => {
    // tsconfig.json is strict JSON on purpose — several scripts read it with
    // JSON.parse — so parse it rather than scraping the text. The two sentinels
    // bracket the generated entries and are inert as exclude patterns.
    const config = JSON.parse(readFileSync(resolve(ROOT, 'tsconfig.json'), 'utf8'));
    const entries: string[] = config.exclude ?? [];
    const begin = entries.findIndex((e) => e.startsWith('__RV-PRIVATE-TEST-EXCLUDES-BEGIN__'));
    const end = entries.indexOf('__RV-PRIVATE-TEST-EXCLUDES-END__');
    expect(begin).toBeGreaterThanOrEqual(0);
    expect(end).toBeGreaterThan(begin);
    expect(entries.slice(begin + 1, end)).toEqual(expected);
  });

  it('never lists itself or the generator guard infrastructure', () => {
    expect(expected).not.toContain('tests/private-test-excludes.node.test.ts');
  });
});
