// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025 realvirtual GmbH <https://realvirtual.io>

/**
 * rv-docs-index — moving an attachment rewrites `docs-index.json`
 * (plan-703 §2.6.5, decision 23, F13).
 *
 * Document links are path-based: `docs-index.json` maps a part number onto a
 * list of `{ title, path }`, and the paths point into `docs/`. So making
 * non-GLB files movable in the tree (decision 23, taken against the planner's
 * recommendation) means the app becomes a **second writer** of a file the build
 * generates.
 *
 * ## The one rule that keeps the two writers from diverging
 *
 * **The app only ever rewrites the `path` of a row that already exists. It never
 * creates a row, never deletes one, and never touches a title.** The build stays
 * the sole author of *what is in* the index; the app only keeps the pointers
 * honest when the user drags a PDF into another folder. That is the mitigation
 * §5.4 asks for, and it is enforced here rather than remembered: there is no
 * function in this module that can add an entry.
 *
 * A move whose old path appears in no row is therefore a **no-op that returns
 * the same object**, not an insertion — a document the build never indexed
 * stays unindexed after being moved, which is the truthful outcome.
 *
 * ## Shape
 *
 * ```json
 * { "4112630": [ { "title": "E BOM", "path": "docs/…/4112630_E_BOM.pdf" } ] }
 * ```
 *
 * Parsed defensively and re-emitted in place: an unknown extra key on a row
 * survives, because the build may well add one and this module is not entitled
 * to an opinion about it.
 */

/** File name at the project root. Generated by the build; patched by the app. */
export const DOCS_INDEX_FILE = 'docs-index.json';

/** One document link. Extra keys are preserved verbatim. */
export interface DocsIndexEntry {
  title: string;
  path: string;
  [key: string]: unknown;
}

/** Part number → its document links. */
export type DocsIndex = Record<string, DocsIndexEntry[]>;

function normalise(path: string): string {
  return (path ?? '').trim().replace(/\\/g, '/').replace(/^\.\//, '').replace(/^\/+/, '');
}

function isEntry(value: unknown): value is DocsIndexEntry {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    && typeof (value as { path?: unknown }).path === 'string';
}

/**
 * Parse a `docs-index.json` payload, dropping only what cannot be a row.
 *
 * Lenient because the file is generated by a build this app does not own: a
 * shape it does not recognise must cost one un-rewritable row, never the whole
 * index. The strict alternative would mean a single malformed entry turning a
 * PDF drag into an error the user cannot fix from inside the viewer.
 */
export function parseDocsIndex(raw: unknown): DocsIndex {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) return {};
  const out: DocsIndex = {};
  for (const [key, value] of Object.entries(raw as Record<string, unknown>)) {
    if (!Array.isArray(value)) continue;
    const entries = value.filter(isEntry);
    if (entries.length > 0) out[key] = entries;
  }
  return out;
}

/** Every distinct path the index points at. */
export function docsIndexPaths(index: DocsIndex): string[] {
  const seen = new Set<string>();
  for (const entries of Object.values(index)) {
    for (const entry of entries) seen.add(normalise(entry.path));
  }
  return [...seen];
}

/** How many rows point at `path`. Zero means a move here changes nothing. */
export function countDocsIndexReferences(index: DocsIndex, path: string): number {
  const wanted = normalise(path);
  let count = 0;
  for (const entries of Object.values(index)) {
    for (const entry of entries) if (normalise(entry.path) === wanted) count++;
  }
  return count;
}

/** One file that moved. */
export interface DocsPathMove {
  from: string;
  to: string;
}

export interface DocsIndexRewriteResult {
  /** The index to persist. **The same object** when nothing matched. */
  index: DocsIndex;
  /** How many rows were repointed. Zero ⇒ the caller can skip its write. */
  rewritten: number;
}

/**
 * Repoint every row that names one of `moves`. Adds nothing, removes nothing.
 *
 * Folder moves are expressed as a list of file moves by the caller
 * (`planTreeMove` already enumerates the descendants), so this function never
 * has to reason about prefixes — which is what keeps `docs/Module_A` from
 * accidentally matching `docs/Module_A_old`.
 *
 * Returns the input object untouched when no row matched, so the caller's write
 * is conditional on an identity comparison rather than on a diff.
 */
export function rewriteDocsIndexPaths(
  index: DocsIndex,
  moves: readonly DocsPathMove[],
): DocsIndexRewriteResult {
  const table = new Map<string, string>();
  for (const move of moves) {
    const from = normalise(move.from);
    const to = normalise(move.to);
    if (from === '' || to === '' || from === to) continue;
    table.set(from, to);
  }
  if (table.size === 0) return { index, rewritten: 0 };

  let rewritten = 0;
  const next: DocsIndex = {};
  for (const [key, entries] of Object.entries(index)) {
    next[key] = entries.map((entry) => {
      const to = table.get(normalise(entry.path));
      if (to === undefined) return entry;
      rewritten++;
      // Spread first so an unknown extra key the build added survives the move.
      return { ...entry, path: to };
    });
  }
  return rewritten === 0 ? { index, rewritten: 0 } : { index: next, rewritten };
}

/** Convenience for the single-file case. */
export function rewriteDocsIndexPath(
  index: DocsIndex,
  from: string,
  to: string,
): DocsIndexRewriteResult {
  return rewriteDocsIndexPaths(index, [{ from, to }]);
}
